POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
  "identifier": "publisher@gmail.com",
  "password": "publisher"
}

###
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
  "username": "test3",
  "email": "test3@gmail.com",
  "password": "test12345"
  ""
}
###
PUT http://localhost:1337/api/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc0NDY0NTE1NiwiZXhwIjoxNzQ3MjM3MTU2fQ.yJAR_dfKPjhHemobU6ZedyCqfqqjIAsO8gudxEFsBxI
Content-Type: application/json

{
  "role": 2
}

###
POST http://localhost:1337/api/user-profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTY1MDgwLCJleHAiOjE3NDcxNjk4ODB9.6af_YFVkt7MDVLBkyVWU4Mqhwua1p7FLj8rAI6oNg5s
Content-Type: application/json

{
  "data": {
    "name": "New User",
    "email": "test2@gmail.com",
    "role": "Advertiser",
    "user": 10
  }
}

###
GET http://localhost:1337/api/marketplaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTMzODU4LCJleHAiOjE3NDcxMzg2NTh9.SYXakgTOQeLWLNWGCTAHLLt8LdXM9ThYcjaNfwgPnkM

###
GET http://localhost:1337/api/api/wallet/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ2NTk5NTYzLCJleHAiOjE3NDcyMDQzNjN9.I4xvWPeELbKbMQ3nBnoLmxpn_nHWF5c9vQcXHYTW17U
###
GET http://localhost:1337/api/api/wallet/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTk2NjQzLCJleHAiOjE3NDcyMDE0NDN9.bG50XXOD1MzGyUXtB1-jdVOcuzoB5cqas8QYrFk8Bz0
###
GET http://localhost:1337/api/api/user-wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTk2NjQzLCJleHAiOjE3NDcyMDE0NDN9.bG50XXOD1MzGyUXtB1-jdVOcuzoB5cqas8QYrFk8Bz0

###
POST http://localhost:1337/api/user-wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTMzODU4LCJleHAiOjE3NDcxMzg2NTh9.SYXakgTOQeLWLNWGCTAHLLt8LdXM9ThYcjaNfwgPnkM
Content-Type: application/json

{
  "balance": "0",
  "escrowBalance": "0",
  "currency": "USD"
}
###
POST http://localhost:1337/api/api/wallet/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ2NTk5NTYzLCJleHAiOjE3NDcyMDQzNjN9.I4xvWPeELbKbMQ3nBnoLmxpn_nHWF5c9vQcXHYTW17U
Content-Type: application/json

{
  "type": "publisher",
  "currency": "USD"
}
###
POST http://localhost:1337/api/api/transactions/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTk2NjQzLCJleHAiOjE3NDcyMDE0NDN9.bG50XXOD1MzGyUXtB1-jdVOcuzoB5cqas8QYrFk8Bz0
Content-Type: application/json

{
  "amount": 1,
  "currency": "USD",
  "gateway": "stripe"
}

###
POST http://localhost:1337/api/api/transactions/webhook/stripe
Content-Type: application/json

{
  "id": "pmc_1RLekuGfw70wnNOgIh74K4gy",
  "type": "payment_intent.succeeded",
  "data": {
    "object": {
      "id": "pi_3RM0hDGfw70wnNOg0kFPDXFM",
      "amount": 1000,
      "currency": "usd",
      "transactionStatus": "success"
    }
  }
}

# > Done! The Stripe CLI is configured for New business sandbox with account id acct_1RLekMGfw70wnNOg