POST http://localhost:1337/api/admin/login
Content-Type: application/json

{
  "identifier": "admin@gmail.com",
  "password": "admin@123"
}

###
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
  "username": "test5",
  "email": "test5@gmail.com",
  "password": "test12345",
  "Advertiser":true
}
###
PUT http://localhost:1337/api/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc0NDY0NTE1NiwiZXhwIjoxNzQ3MjM3MTU2fQ.yJAR_dfKPjhHemobU6ZedyCqfqqjIAsO8gudxEFsBxI
Content-Type: application/json

{
  "role": 2
}

###
POST http://localhost:1337/api/user-profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc0NzAyNzA2MywiZXhwIjoxNzQ3NjMxODYzfQ.h0hCqxgzbjpNnSZdwNN1mj9O_v2xTcdWfRaELDHxs_Q
Content-Type: application/json

{
  "data": {
    "name": "New User",
    "email": "test2@gmail.com",
    "role": "Advertiser",
    "user": 10
  }
}

###
GET http://localhost:1337/api/marketplaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTMzODU4LCJleHAiOjE3NDcxMzg2NTh9.SYXakgTOQeLWLNWGCTAHLLt8LdXM9ThYcjaNfwgPnkM

###
GET http://localhost:1337/api/api/wallet/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQ2NjI0NTU5LCJleHAiOjE3NDcyMjkzNTl9.vqFlFP2TS9hxeiT5IPIBrZ7ThnPhBhkd0f9JtNDuj-g
###
GET http://localhost:1337/api/api/wallet/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQ2NjI0NTU5LCJleHAiOjE3NDcyMjkzNTl9.vqFlFP2TS9hxeiT5IPIBrZ7ThnPhBhkd0f9JtNDuj-g
###
GET http://localhost:1337/api/api/user-wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQ2NjI0NTU5LCJleHAiOjE3NDcyMjkzNTl9.vqFlFP2TS9hxeiT5IPIBrZ7ThnPhBhkd0f9JtNDuj-g

###
POST http://localhost:1337/api/user-wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzQ2NjEyMDMxLCJleHAiOjE3NDcyMTY4MzF9.KsXbrLJ7Uk5iC0bYDFJZbSsBxapZtY5cMGXY8unLr8M
Content-Type: application/json

{
  "balance": "0",
  "escrowBalance": "0",
  "currency": "USD"
}
###
POST http://localhost:1337/api/api/wallet/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQ2NjI0NTU5LCJleHAiOjE3NDcyMjkzNTl9.vqFlFP2TS9hxeiT5IPIBrZ7ThnPhBhkd0f9JtNDuj-g
Content-Type: application/json

{
  "type": "advertiser",
  "currency": "USD"
}
###
POST http://localhost:1337/api/api/transactions/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQ2NjI0NTU5LCJleHAiOjE3NDcyMjkzNTl9.vqFlFP2TS9hxeiT5IPIBrZ7ThnPhBhkd0f9JtNDuj-g
Content-Type: application/json

{
  "amount": 1,
  "currency": "USD",
  "gateway": "paypal"
}

###
POST http://localhost:1337/api/api/transactions/webhook/stripe
Content-Type: application/json

{
  "id": "pmc_1RLekuGfw70wnNOgIh74K4gy",
  "type": "payment_intent.succeeded",
  "data": {
    "object": {
      "id": "pi_3RM85oGfw70wnNOg1uSN9O78",
      "amount": 1,
      "currency": "usd",
      "transactionStatus": "success"
    }
  }
}


###
POST http://localhost:1337/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc0NzAyNzIyNCwiZXhwIjoxNzQ3NjMyMDI0fQ.s-gKcuZwEv_TMZks6JA65xk_6xynDVzA71CNU4tH_ng
Content-Type: application/json

{
  "totalAmount": "1000",
  "description": "description",
  "website":"keymaker3.com"
}
###
GET http://localhost:1337/api/orders/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc0NzAyNzIyNCwiZXhwIjoxNzQ3NjMyMDI0fQ.s-gKcuZwEv_TMZks6JA65xk_6xynDVzA71CNU4tH_ng


###
GET http://localhost:1337/api/admin/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImlhdCI6MTc0ODkzMTE5MiwiZXhwIjoxNzQ5NTM1OTkyfQ.kR6enUqwFdRjNEgvH3hd32u0IgbZt1RL4iGbgwB09t0
###
PUT http://localhost:1337/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ4NTg3ODExLCJleHAiOjE3NDkxOTI2MTF9.BnX0Qr7RQy52I_a_Q8uV7VgLRB2Qn9FZM8eabs5OcGw
Content-Type: application/json

{
  "businessName": "test",
  "billingAddress": "USD",
  "billingAddress": "paypal"
}

# > Done! The Stripe CLI is configured for New business sandbox with account id acct_1RLekMGfw70wnNOg